version: "3.8"

services:
  web:
    image: postgres:latest
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/code
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: "${DB_USER_ID}"
      POSTGRES_PASSWORD: "${DB_USER_PASSWORD}"
      # POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data

volumes:
  postgres_data:
