version: "3.8"

services:
  # web:
  #   image: postgres:latest
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - FLASK_ENV=development
  #   volumes:
  #     - .:/code
  #   depends_on:
  #     - db

  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      # POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data

volumes:
  postgres_data:
